'use strict';
// Stable hero IDs also connect future 3D appearances, portraits and combat sprites.
const CHARACTER_DESIGNS={
 oak:{stars:4,tone:'#739783',personality:['沉稳 · 可靠 · 守护者','Steadfast · Patient · Protective','穏やか · 頼れる · 守護者'],bio:['习惯最后一个离开训练场。看似不善言辞，却记得每个人的伤口和归期。橄榄绿披肩与橡叶盾徽，是他不轻易说出口的承诺。','Always the last to leave training. Quiet, yet he remembers every wound and every homecoming. His olive cape and oak shield carry an unspoken promise.','訓練場を最後に去る人。口数は少ないが、仲間の傷と帰る日を覚えている。オリーブの肩掛けと樫の盾は、言葉にしない約束。']},
 arrow:{stars:4,tone:'#77ab92',personality:['开朗 · 自由 · 行动派','Playful · Free-spirited · Daring','陽気 · 自由 · 行動派'],bio:['喜欢给沉闷的任务起绰号，遇险时却总是第一个回头。翡翠色马尾、轻装短披风与折叠长弓，让她像穿过雨夜的一阵风。','She gives dull missions ridiculous nicknames, but always turns back first when a friend is in trouble. Emerald hair and a light cape follow her folding bow.','退屈な任務におかしな名前をつける。けれど仲間が危ない時は真っ先に戻る。翡翠の髪と軽いマントが、折り畳み弓と共に風を切る。']},
 ember:{stars:5,tone:'#d58172',personality:['热烈 · 倔强 · 不服输','Passionate · Stubborn · Fearless','情熱的 · 頑固 · 負けず嫌い'],bio:['把恐惧藏在笑声里，讨厌任何人替自己决定结局。赤铜长发、黑红作战礼装和火晶耳饰，是她向长夜发出的挑战。','She hides fear in laughter and refuses to let anyone choose her ending. Copper hair, a black-and-crimson coat and flame crystal earrings challenge the night.','恐怖を笑い声で隠し、自分の結末を他人に決めさせない。赤銅の髪、黒と深紅の礼装、炎晶の耳飾りで夜に挑む。']},
 sage:{stars:5,tone:'#81b5ae',personality:['温柔 · 细腻 · 理想主义','Gentle · Attentive · Idealistic','優しい · 繊細 · 理想主義'],bio:['会在任务报告的空白处画花。相信救下一个人也足以改变世界。薄荷色卷发、圆框眼镜与象牙白医师长衣，让人愿意放下戒备。','He sketches flowers in report margins and believes saving one person can change the world. Mint waves, round glasses and an ivory medical coat put others at ease.','報告書の余白に花を描く。一人を救うことにも世界を変える力があると信じる。ミント色の髪、丸眼鏡、象牙色の白衣が心を和らげる。']},
 knight:{stars:6,tone:'#d6b66d',personality:['正直 · 克制 · 坚定','Honorable · Composed · Resolute','誠実 · 冷静 · 意志が強い'],bio:['对誓言近乎固执，却会为了保护眼前的人质疑命令。晨金发色与白金铠甲象征黎明，深蓝披风则提醒他记住仍在黑夜中的人。','Loyal to his vows, yet willing to question orders to protect a life. Golden hair and ivory armor greet the dawn; a navy cape remembers those still in darkness.','誓いを守り、目の前の命を救うためなら命令を疑う。金髪と白金の鎧は暁、紺のマントはまだ夜にいる人々への想い。']},
 frost:{stars:5,tone:'#8cbacb',personality:['安静 · 敏锐 · 外冷内热','Reserved · Perceptive · Caring','寡黙 · 鋭敏 · 内に優しさ'],bio:['总能听见别人忽略的声音。寡言不是疏远，而是认真倾听。冰蓝短发、高领白衣与水晶法杖，包裹着比雪更柔软的心。','She hears what others miss. Her silence is careful listening, not distance. Ice-blue hair, a white high collar and crystal staff shelter a tender heart.','皆が聞き逃す声に気づく。沈黙は拒絶ではなく、耳を傾けるため。氷青の髪、白い襟、水晶の杖に柔らかな心を隠す。']},
 warden:{stars:5,tone:'#a098c0',personality:['寡言 · 自律 · 重诺','Taciturn · Disciplined · Loyal','無口 · 自律 · 約束を守る'],bio:['从不询问同伴不愿讲述的过去。只要约定还在，他就会守到最后。紫黑制服、半面银饰与六角符文护臂记录着被保护者的名字。','He never asks about a past a friend would rather leave buried. His violet-black uniform, silver half-mask and rune gauntlets carry the names of those he protects.','仲間が話したがらない過去を尋ねない。約束がある限り守り抜く。紫黒の制服、銀の半面、符文の腕甲には守る人の名が刻まれる。']},
 moon:{stars:6,tone:'#b3a3cf',personality:['独立 · 清醒 · 温柔藏锋','Independent · Lucid · Quietly kind','自立 · 明晰 · 静かな優しさ'],bio:['习惯独自行动，却会把最安全的退路留给同伴。银尾黑发、月牙银扣与象牙色长衣，像一封从未寄出的温柔来信。','She works alone, but leaves the safest escape for her companions. Silver-tipped black hair, crescent clasps and ivory coat tails resemble an unsent letter of kindness.','単独行動を好むが、最も安全な退路を仲間に残す。銀に染まる黒髪、三日月の留め具、象牙色の長衣は、出せなかった優しい手紙のよう。']}
};
for(const hero of HEROES)hero.stars=CHARACTER_DESIGNS[hero.id].stars;
// Portraits and cinematic cut-ins share the revised designs; combat chibis keep their own assets.
const characterImage=(id,kind='portrait')=>'assets/characters/'+id+'-'+(kind==='portrait'||kind==='ultimate'?'portrait-v2':kind)+'.png';
const characterText=(id,key)=>CHARACTER_DESIGNS[id][key][{zh:0,en:1,ja:2}[language]];
const starText=id=>'★'.repeat(CHARACTER_DESIGNS[id]?.stars||0);
const CHARACTER_SPRITES={};
if(typeof Image!=='undefined')for(const id of Object.keys(CHARACTER_DESIGNS)){const img=new Image();img.src=characterImage(id,'chibi');CHARACTER_SPRITES[id]=img;}
Object.assign(TEXT,{
 atrium:['星穹中庭','CELESTIAL ATRIUM','星穹の中庭'],storyButton:['剧情','STORY','物語'],allCharacters:['全部角色','CHARACTERS','キャラクター'],warehouse:['仓库','INVENTORY','倉庫'],more:['扩展','MORE','その他'],moreTitle:['扩展菜单','More options','拡張メニュー'],collectionSubtitle:['与你同行的八位同伴','Eight companions by your side','共に歩む八人の仲間'],characterProfile:['角色档案','CHARACTER PROFILE','キャラクターファイル'],personality:['性格','PERSONALITY','性格'],featuredNow:['当前大厅展示','Featured in the atrium','ロビー展示中'],chooseDisplay:['点击头像，切换大厅展示角色','Choose a portrait to feature in the lobby','肖像を選ぶとロビーの展示が切り替わります'],
 rarity:['{n} 星','{n}-STAR','★{n}'],rarityNote:['星级为角色初始稀有度，本版本不含升星。','Stars indicate base rarity. Ascension is not part of this demo.','星は初期レアリティです。この版に昇星機能はありません。'],ultimateTalent:['六星专属 · 全屏技能演出','6-STAR · FULL-SCREEN SKILL CINEMATIC','★6専用 · 全画面スキル演出'],ultimateKicker:['六星觉醒','SIX-STAR AWAKENING','六星覚醒'],
 fullEffects:['六星全屏演出','Six-star cinematics','★6全画面演出'],idleMotion:['大厅动态立绘','Animated lobby portraits','ロビー立ち絵の動き'],settingsSaved:['设置自动保存在本机','Settings save on this device','設定は端末に自動保存されます'],
 relics:['剧情收藏','STORY RELICS','物語の収集品'],relicHint:['通关各幕后获得纪念物，记录你们共同走过的旅程。','Clear each act to collect a keepsake from your journey.','各幕をクリアすると、旅の記念品が手に入ります。'],relicEmpty:['尚未获得纪念物。完成第一幕后，再回来看看。','No keepsakes yet. Return after clearing the first act.','記念品はまだありません。第一幕をクリアして戻ってきましょう。'],relicCount:['已收集 {n} / 5','{n} / 5 collected','収集済み {n} / 5'],ownedSkins:['已拥有外观','OWNED APPEARANCES','所持している外見'],skinHint:['每位角色均拥有一款基础外观，可在全部角色中展示。','Each companion owns a base appearance, available in Characters.','全員の基本衣装を所持。「キャラクター」で展示できます。'],
 relicLetter:['密封的录取信','Sealed admission letter','封印された入学通知'],relicKey:['观测站密钥','Observatory key','観測所の鍵'],relicPhoto:['旧档案中的合影','Archive photograph','古い記録の集合写真'],relicStar:['孩子折的纸星星','A child’s paper star','子供が折った紙の星'],relicBell:['停摆的钟芯','Silent clockwork','止まった時計の芯'],
 relicLetterDesc:['车站留下的信，收件日期是十年前。','A station letter dated ten years ago.','十年前の日付が書かれた、駅で受け取った手紙。'],relicKeyDesc:['守住观测站后，交到你手中的银色密钥。','The silver key entrusted to you after the siege.','観測所を守った後に託された銀色の鍵。'],relicPhotoDesc:['背面写着那个从记录里消失的名字。','On its back, a name erased from history.','裏には、記録から消された名前。'],relicStarDesc:['歪歪的折痕里，藏着一个获救家庭的感谢。','Its crooked folds hold a rescued family’s gratitude.','不揃いの折り目に、救われた家族の感謝がこもる。'],relicBellDesc:['钟声停下了，但下一封来信已经在路上。','The bell fell silent. Another letter is on its way.','鐘は止まった。次の手紙は、もう届こうとしている。'],
 backToArchive:['返回剧情档案','Back to story archive','物語アーカイブへ'],portraitUnavailable:['角色资源未加载','Character artwork unavailable','キャラクター画像を読み込めません']
});
