'use strict';
let collectionState=null,gachaBanner='limited-character',gachaBusy=false,gachaPending=null,gachaResults=[],gachaError='';
const gachaLoc=a=>a[{zh:0,en:1,ja:2}[language]];
const CARD_DESIGNS={
 moon:{art:'assets/cards/moon-card-v1.png',tone:'moon',edition:'MS-008',title:['月下回信','A Moonlit Reply','月下の返事'],line:['别回头。今晚的月光，会替你照亮归途。','Keep moving. Tonight, the moon will light your way home.','振り返らないで。今夜の月が、帰り道を照らすから。']},
 knight:{art:'assets/cards/knight-card-v1.png',tone:'dawn',edition:'MS-005',title:['黎明誓约','The Oath of Dawn','暁の誓約'],line:['只要还有一个人等待黎明，我的剑就不会熄灭。','As long as someone waits for dawn, my blade will not fade.','夜明けを待つ人がいる限り、この剣の光は消えない。']},
 frost:{art:'assets/cards/frost-card-v1.png',tone:'frost',edition:'MS-006',title:['冰海来信','Letters from the Frozen Sea','氷海からの便り'],line:['冰层之下，那些未说出口的话还在回响。','Beneath the ice, unspoken words still echo.','氷の下では、言えなかった言葉がまだ響いている。']},
 ember:{art:'assets/cards/ember-card-v1.png',tone:'ember',edition:'MS-003',title:['余烬长夜','Embers of the Long Night','長い夜の残火'],line:['结局由我们来写。先把这片黑夜，烧出一道光。','We write our own ending. First, let us kindle a light in this night.','結末は私たちが書く。まず、この夜に光を灯そう。']},
 oak:{tone:'grove',edition:'MS-001',title:['归途守望','A Promise of Home','帰路の守り'],line:['放心向前。你们身后，还有我。','Go ahead. I will watch your backs.','安心して進んでくれ。後ろは私が守る。']},
 arrow:{tone:'wind',edition:'MS-002',title:['风的邀约','An Invitation from the Wind','風の招待'],line:['听，风已经出发了。我们也走吧！','Listen—the wind is on its way. Shall we follow?','ほら、風はもう出発したよ。私たちも行こう！']},
 sage:{tone:'grove',edition:'MS-004',title:['微光新芽','A Seed of Light','微かな光の芽'],line:['每一次呼吸，都值得被温柔守护。','Every breath is worth protecting.','ひとつひとつの息を、優しく守りたい。']},
 warden:{tone:'rune',edition:'MS-007',title:['无声之誓','The Silent Vow','声なき誓い'],line:['不必解释你的过去。我守的是现在的你。','You need not explain your past. I protect who you are now.','過去を語らなくていい。今の君を守る。']}
};
let gachaRevealPhase='idle',gachaRevealIndex=0,gachaInspectItem=null,gachaInspectReturn=null;
function syncGachaFocusLayers(){const busyLayer=!!gachaResults.length||!!gachaInspectItem;const layout=$('#gacha-dialog .gacha-layout'),heading=$('#gacha-dialog .modal-heading'),results=$('#gacha-result');if(layout)layout.inert=busyLayer;if(heading)heading.inert=busyLayer;if(results)results.inert=!!gachaInspectItem;}
function resetGachaPresentation(){gachaRevealPhase='idle';gachaRevealIndex=0;gachaInspectItem=null;gachaInspectReturn=null;const viewer=$('#gacha-art-view');if(viewer)viewer.hidden=true;const reveal=$('#gacha-reveal');if(reveal)reveal.hidden=true;const result=$('#gacha-result');if(result)result.hidden=true;syncGachaFocusLayers();}
function resetGachaSession(){gachaBusy=false;gachaPending=null;gachaResults=[];gachaError='';gachaBanner='limited-character';resetGachaPresentation();}
function collectionContext(){const generation=accountGeneration,id=accountUser.id;return {key:'wilds.pending.draw.'+id,current:()=>accountGeneration===generation&&accountUser?.id===id};}
Object.assign(TEXT,{
 summon:['招募','RECRUIT','募集'],summonSubtitle:['与星光相遇','Meet beneath the stars','星の下で出会う'],tickets:['招募券','Recruit tickets','募集券'],dust:['星尘','Stardust','星塵'],singleDraw:['招募一次 · 1 券','Recruit ×1 · 1 ticket','1回募集・1枚'],tenDraw:['招募十次 · 10 券','Recruit ×10 · 10 tickets','10回募集・10枚'],drawWorking:['星光正在回应…','Awaiting a reply…','星からの返事を待っています…'],drawRetry:['确认上次招募结果','Recover last recruitment','前回の結果を確認'],drawNew:['新获得','NEW','新規'],drawDuplicate:['重复 → 星尘 +{n}','Duplicate → +{n} dust','重複 → 星塵+{n}'],drawResults:['星光回响','A reply from the stars','星からの返事'],drawHistory:['最近 100 条记录','Last 100 results','直近100件'],drawRules:['概率与规则','Rates & rules','確率とルール'],drawRulesText:['六星基础概率 2%，五星 8%，四星 90%。每个卡池独立累计：最多 60 抽必得六星，最多 10 抽必得五星或以上；获得六星同时重置两种保底，获得五星只重置十抽保底。保底触发时，六星优先。限定池六星必为当期展示角色或武器，没有歪池或 50/50；常驻池不含限定六星。本期为无截止日期的测试卡池。重复四 / 五 / 六星转为 10 / 50 / 200 星尘，100 星尘可换 1 券。初始 60 券，每关首次通关再送 10 券。无付费入口。',
 'Base rates: 6★ 2%, 5★ 8%, 4★ 90%. Each banner has separate pity: 6★ within 60 pulls; 5★ or higher within 10. A 6★ resets both counters, a 5★ only the ten-pull counter. Six-star pity takes priority. Limited 6★ is always the featured item; no 50/50. Standard banners exclude limited 6★. This demo banner has no end date. Duplicates grant 10 / 50 / 200 dust by rarity; 100 dust = 1 ticket. Start with 60 tickets; each first stage clear grants 10. No purchases.',
 '基本確率：★6は2%、★5は8%、★4は90%。各募集の天井は独立。60回以内に★6、10回以内に★5以上を獲得。★6で両カウンター、★5で10回分のみリセット。★6天井が優先。限定の★6は必ずピックアップ対象。恒常に限定★6は含まれません。テスト期間中は終了日なし。重複は★4/5/6で星塵10/50/200に変換。100星塵で1枚。開始時60枚、各ステージ初回クリアで10枚。課金なし。'],
 pitySix:['六星保底：还需最多 {n} 抽','6★ guaranteed within {n} pulls','★6確定まで最大{n}回'],pityFive:['五星或以上：还需最多 {n} 抽','5★ or higher within {n} pulls','★5以上まで最大{n}回'],poolContents:['本池包含','Pool contents','排出対象'],lockedCharacter:['未拥有 · 招募获得','Locked · Recruit to unlock','未所持・募集で獲得'],ownedRoster:['主角 + {n} / 8 位伙伴','Protagonist + {n} / 8 companions','主人公＋仲間{n}/8人'],notEnoughTickets:['招募券不足，可首次通关获取。','Not enough tickets. Earn more with first clears.','券が不足しています。初回クリアで獲得できます。'],notEnoughDust:['星尘不足 100。','You need 100 dust.','星塵100が必要です。'],invalidDraw:['请求无效，请重新进入招募。','Invalid request. Reopen recruitment.','無効な要求です。募集を開き直してください。'],heroLocked:['这个角色尚未获得。','You do not own this character.','このキャラクターは未所持です。'],exchangeDust:['100 星尘 → 1 招募券','100 dust → 1 ticket','100星塵 → 募集券1枚'],weaponsTitle:['已拥有武器','Owned weapons','所持武器'],equipWeapon:['装备','Equip','装備'],unequipWeapon:['卸下','Unequip','外す'],weaponBonus:['攻击 +{atk} · 技能强度 +{power}','ATK +{atk} · Skill power +{power}','攻撃+{atk}・スキル威力+{power}'],weaponHint:['每位伙伴可装备一把武器，同一武器只能由一人使用。重复武器转换为星尘。','One weapon per companion; each weapon equips to one companion. Duplicates become dust.','仲間1人に武器1つ。同じ武器の同時装備は不可。重複は星塵に変換。'],weaponEmpty:['尚未获得武器，可在招募中获取。','Recruit from an arms banner to obtain weapons.','武器募集で武器を獲得できます。'],historyEmpty:['还没有招募记录。','No recruitment yet.','募集履歴はありません。'],drawClose:['收下回响','Accept','受け取る']
});
Object.assign(TEXT,{
 cardGallery:['卡面鉴赏','Card gallery','カード鑑賞'],cardGalleryHint:['免费预览全部角色卡面','Preview every character card for free','全キャラクターを無料で鑑賞'],cardArtwork:['角色卡面','Character artwork','キャラクターカード'],cardReveal:['点亮星轨','Reveal the starlight','星の軌跡を開く'],cardNext:['下一道回响','Next reveal','次の響きへ'],cardOverview:['查看全部结果','View all results','結果をすべて見る'],cardSkip:['跳过演出','Skip reveal','演出をスキップ'],cardRevealProgress:['第 {n} / {total} 道回响','REVEAL {n} / {total}','{n} / {total} 番目の響き'],cardRevealHint:['点击卡牌或下方按钮揭晓','Select the card or button to reveal','カードまたはボタンで開く'],cardResultHint:['点击卡面，可欣赏完整原画','Select a card to view the full artwork','カードを選ぶと原画を鑑賞できます'],cardSixArrival:['六星 · 星辉降临','SIX-STAR · STELLAR ARRIVAL','六星・星の降臨'],cardSkill:['专属技能','SIGNATURE SKILL','専用スキル'],cardTraits:['羁绊','TRAITS','特性'],cardOwned:['已拥有','OWNED','所持済み'],cardPreviewOnly:['鉴赏模式 · 不消耗招募券','GALLERY · NO TICKETS USED','鑑賞モード・券の消費なし'],cardBack:['返回','Back','戻る'],cardSeries:['晨星档案','MORNINGSTAR ARCHIVE','晨星アーカイブ']
});
function cardDesign(item){return item.kind==='character'?CARD_DESIGNS[item.id]:{tone:item.id==='crescent'?'moon':item.id==='daybreak'?'dawn':item.id==='flame'?'ember':item.id==='crystal'?'frost':'rune',edition:'AR-'+String(Object.keys(GACHA_DATA.weapons).indexOf(item.id)+1).padStart(3,'0')};}
function cardImage(item){return CARD_DESIGNS[item.id]?.art||characterImage(item.id);}
function weaponCardArt(item){const paths={crescent:'M146 42 C75 52 69 144 139 167 C105 160 104 100 146 42 M139 167 L95 233 M112 195 L141 206',daybreak:'M119 35 L143 80 L129 182 L146 201 L126 207 L125 244 L113 244 L112 207 L91 201 L108 182 L95 80 Z',flame:'M64 102 L112 87 L166 100 L166 216 L116 230 L64 214 Z M116 108 L116 216 M129 70 C166 22 158 95 136 111 C145 78 111 81 129 70',crystal:'M120 33 L147 68 L120 107 L92 68 Z M120 108 L120 239 M96 110 L143 110 M103 121 L136 121',rune:'M143 36 L157 57 L128 174 L140 188 L121 195 L108 237 L96 231 L109 190 L97 172 L113 170 Z',practice:'M120 42 L133 68 L125 174 L146 185 L125 192 L125 236 L114 236 L114 192 L93 185 L113 174 L107 68 Z',field:'M120 64 L161 110 L143 170 L98 170 L79 110 Z M119 170 L119 222 M96 226 L145 226'};return '<svg class="weapon-card-art" viewBox="0 0 240 280" aria-hidden="true"><g class="armament-orbits" fill="none" stroke="currentColor"><circle cx="120" cy="140" r="94"/><circle cx="120" cy="140" r="77"/><path d="M120 26 L220 197 L20 197 Z M22 83 L219 83 L120 254 Z"/></g><path class="armament-blade" d="'+paths[item.id]+'"/><circle cx="120" cy="140" r="5" fill="currentColor"/></svg>';}
function cardFace(item,index,interactive=false){const design=cardDesign(item),hero=item.kind==='character'?heroText(def(item.id)):null,art=hero?'<img class="card-art '+(design.art?'scene-art':'portrait-art')+'" src="'+cardImage(item)+'" alt="" loading="eager">':weaponCardArt(item);return '<'+(interactive?'button type="button"':'div')+' class="draw-card rarity-'+item.stars+' tone-'+design.tone+'" '+(interactive?'data-card-index="'+index+'" aria-label="'+itemName(item)+' — '+tr('cardArtwork')+'"':'')+'><span class="card-ornament" aria-hidden="true"></span>'+art+'<span class="card-foil" aria-hidden="true"></span><span class="card-edition">'+design.edition+'</span><span class="card-rank">'+item.stars+'<small>★</small></span><div class="card-caption"><span class="card-stars">'+'★'.repeat(item.stars)+'</span><strong>'+itemName(item)+'</strong><span class="card-subtitle">'+(hero?gachaLoc(design.title):tr('weaponBonus',GACHA_DATA.weapons[item.id]))+'</span>'+(item.duplicate!==undefined?'<small class="card-acquisition '+(!item.duplicate?'is-new':'')+'">'+tr(item.duplicate?'drawDuplicate':'drawNew',{n:item.dust})+'</small>':'')+'</div></'+(interactive?'button':'div')+'>';}
function beginGachaReveal(){resetGachaPresentation();gachaRevealPhase='sealed';gachaRevealIndex=0;renderGachaResults();$('#gacha-reveal-next').focus();}
function renderGachaResults(){
 const hasResults=!!gachaResults.length,sequence=hasResults&&gachaRevealPhase!=='overview'&&gachaRevealPhase!=='idle';syncGachaFocusLayers();$('#gacha-result').hidden=!hasResults;$('#gacha-reveal').hidden=!sequence;$('#gacha-results').hidden=sequence;$('#gacha-result-close').hidden=sequence;$('#gacha-result-hint').hidden=sequence;$('#gacha-result-heading').hidden=sequence;
 $('#gacha-results').innerHTML=hasResults?gachaResults.map((item,i)=>cardFace(item,i,true)).join(''):'';
 if(!sequence)return;const item=gachaResults[gachaRevealIndex],revealed=gachaRevealPhase==='revealed',design=cardDesign(item),reveal=$('#gacha-reveal');reveal.dataset.phase=gachaRevealPhase;reveal.dataset.rarity=item.stars;reveal.dataset.tone=design.tone;
 $('#gacha-reveal-progress').textContent=tr('cardRevealProgress',{n:gachaRevealIndex+1,total:gachaResults.length});$('#gacha-reveal-kicker').textContent=revealed&&item.stars===6?tr('cardSixArrival'):tr('drawResults');
 $('#gacha-reveal-card').innerHTML=revealed?cardFace(item,gachaRevealIndex):'<div class="sealed-card"><div class="seal-orbit"></div><span class="seal-star">✧</span><span class="seal-brand">MORNINGSTAR</span><span class="seal-number">'+String(gachaRevealIndex+1).padStart(2,'0')+'</span></div>';
 $('#gacha-reveal-card').setAttribute('aria-label',tr(revealed?'cardNext':'cardReveal'));$('#gacha-reveal-hint').textContent=revealed?(item.kind==='character'?gachaLoc(design.line):tr('weaponBonus',GACHA_DATA.weapons[item.id])):tr('cardRevealHint');$('#gacha-reveal-next').textContent=tr(!revealed?'cardReveal':gachaRevealIndex===gachaResults.length-1?'cardOverview':'cardNext');
}
function advanceGachaReveal(){if(!gachaResults.length)return;if(gachaRevealPhase==='sealed')gachaRevealPhase='revealed';else if(gachaRevealIndex<gachaResults.length-1){gachaRevealIndex++;gachaRevealPhase='sealed';}else gachaRevealPhase='overview';renderGachaResults();if(gachaRevealPhase==='overview')$('#gacha-result-close').focus();}
function skipGachaReveal(){if(!gachaResults.length)return;gachaRevealPhase='overview';renderGachaResults();$('#gacha-result-close').focus();}
function openCardArtwork(item,source=null){gachaInspectItem={...item};gachaInspectReturn=source;syncGachaFocusLayers();renderCardArtwork();$('#gacha-art-view').hidden=false;$('#gacha-art-close').focus();}
function renderCardArtwork(){if(!gachaInspectItem)return;const item=gachaInspectItem,design=cardDesign(item),hero=item.kind==='character'?heroText(def(item.id)):null;$('#gacha-art-view').dataset.tone=design.tone;$('#gacha-art-display').innerHTML=hero?'<img src="'+cardImage(item)+'" class="'+(design.art?'scene-art':'portrait-art')+'" alt="'+hero.name+'">':weaponCardArt(item);$('#gacha-art-stars').textContent='★'.repeat(item.stars);$('#gacha-art-title').textContent=itemName(item);$('#gacha-art-subtitle').textContent=hero?gachaLoc(design.title):tr('weaponBonus',GACHA_DATA.weapons[item.id]);$('#gacha-art-line').textContent=hero?gachaLoc(design.line):tr('weaponHint');$('#gacha-art-skill').textContent=hero?hero.skill:'';$('#gacha-art-skill-desc').textContent=hero?hero.desc:'';$('#gacha-art-traits').textContent=hero?hero.traits.map(t=>traitText(t).name).join(' / '):'';$('#gacha-art-character-info').hidden=!hero;$('#gacha-art-status').textContent=(hero?collectionState?.heroes.includes(item.id):collectionState?.weapons[item.id])?tr('cardOwned'):tr('cardPreviewOnly');$('#gacha-gallery-list').hidden=!hero;$('#gacha-gallery-list').innerHTML=hero?HEROES.map(h=>'<button type="button" data-gallery-id="'+h.id+'" aria-pressed="'+(h.id===item.id)+'" aria-label="'+heroText(h).name+'"><img src="'+characterImage(h.id)+'" alt=""><span>'+heroText(h).name+'</span></button>').join(''):'';}
function closeCardArtwork(){gachaInspectItem=null;$('#gacha-art-view').hidden=true;syncGachaFocusLayers();if(gachaInspectReturn?.isConnected)gachaInspectReturn.focus();else $(gachaResults.length?'#gacha-result-close':'#gacha-gallery-open').focus();gachaInspectReturn=null;}
function setCollection(state){
 if(!state)return;collectionState=state;
 OWNED_HEROES.splice(0,OWNED_HEROES.length,...state.heroes);
 for(const id of state.heroes)if(!skinByHero[id])skinByHero[id]='base';
}
function itemName(item){return item.kind==='character'?heroText(def(item.id)).name:gachaLoc(GACHA_DATA.weapons[item.id].name);}
function itemArt(item){return item.kind==='character'?'<img src="'+cardImage(item)+'" alt="">':weaponCardArt(item);}
function gachaPendingKey(){return 'wilds.pending.draw.'+accountUser.id;}
function renderGacha(){
 if(!collectionState)return;const banner=GACHA_DATA.banners.find(b=>b.id===gachaBanner),pity=collectionState.pity[banner.id];
 $('#gacha-tabs').innerHTML=GACHA_DATA.banners.map((b,i)=>'<button role="tab" aria-selected="'+(b.id===banner.id)+'" data-banner="'+b.id+'" '+(gachaBusy||gachaPending?'disabled':'')+'><small>0'+(i+1)+' / '+(b.kind==='character'?'PERSONNEL':'ARMAMENT')+'</small><strong>'+gachaLoc(b.name)+'</strong></button>').join('');
 $('#gacha-wallet').textContent=tr('tickets')+' '+collectionState.tickets+'   /   '+tr('dust')+' '+collectionState.dust;
 $('#gacha-title').textContent=gachaLoc(banner.name);$('#gacha-feature').innerHTML=itemArt({kind:banner.kind,id:banner.featured});$('#gacha-feature').dataset.kind=banner.kind;
 $('#gacha-feature-name').textContent=itemName({kind:banner.kind,id:banner.featured});$('#gacha-feature-line').textContent=banner.kind==='character'?gachaLoc(CARD_DESIGNS[banner.featured].line):tr('weaponBonus',GACHA_DATA.weapons[banner.featured]);$('#gacha-dialog').dataset.banner=banner.id;
 $('#gacha-pity-six').textContent=tr('pitySix',{n:60-pity.six});$('#gacha-pity-five').textContent=tr('pityFive',{n:10-pity.five});
 $('#gacha-pool').textContent=tr('poolContents')+' · '+[6,5,4].map(stars=>'★'+stars+' '+banner[stars===6?'six':stars===5?'five':'four'].map(id=>itemName({id,kind:banner.kind})).join(' / ')).join(' · ');
 $('#gacha-error').textContent=gachaError?accountErrorMessage(gachaError):'';
 for(const n of [1,10]){const button=$('#draw-'+n);button.disabled=gachaBusy||(!gachaPending&&collectionState.tickets<n)||!!gachaPending&&n!==gachaPending.count;button.textContent=tr(gachaBusy?'drawWorking':gachaPending?'drawRetry':n===1?'singleDraw':'tenDraw');}
 $('#gacha-exchange').disabled=gachaBusy||!!gachaPending||collectionState.dust<100;
 renderGachaResults();renderCardArtwork();
 $('#gacha-history').innerHTML=collectionState.history.length?collectionState.history.map(item=>'<li><span>'+new Date(item.time).toLocaleString(language==='zh'?'zh-CN':language==='ja'?'ja-JP':'en-US')+'</span><b>'+'★'.repeat(item.stars)+' '+itemName(item)+'</b><small>'+gachaLoc(GACHA_DATA.banners.find(b=>b.id===item.banner).name)+'</small></li>').join(''):'<li>'+tr('historyEmpty')+'</li>';
}
async function openGacha(){
 if(!accountUser||gachaBusy)return;const context=collectionContext();resetGachaPresentation();openUtilityDialog('gacha-dialog');gachaResults=[];gachaError='';gachaPending=null;gachaBusy=true;renderGacha();
 try{gachaPending=JSON.parse(localStorage.getItem(context.key)||'null');if(gachaPending)gachaBanner=gachaPending.banner;const data=await accountApi('collection');if(context.current())setCollection(data.collection);}catch(e){if(context.current())gachaError=e.message;}
 finally{if(context.current()){gachaBusy=false;renderGacha();}}
}
async function performDraw(count){
 if(gachaBusy||!accountUser)return;const context=collectionContext();resetGachaPresentation();gachaBusy=true;gachaError='';gachaResults=[];renderGacha();
 try{
  await flushAccountSave();if(!context.current())return;if(!gachaPending){gachaPending={banner:gachaBanner,count,requestId:crypto.randomUUID()};localStorage.setItem(context.key,JSON.stringify(gachaPending));}
  const result=await accountApi('draw','POST',gachaPending);localStorage.removeItem(context.key);if(!context.current())return;gachaPending=null;setCollection(result.collection);gachaResults=result.results;renderLobby();renderRoster();
 }catch(e){if(e.message!=='networkError'&&e.message!=='serverError')localStorage.removeItem(context.key);if(context.current()){gachaError=e.message;if(e.message!=='networkError'&&e.message!=='serverError')gachaPending=null;}}
 finally{if(context.current()){gachaBusy=false;renderGacha();if(gachaResults.length&&$('#gacha-dialog').open){beginGachaReveal();if(!presentationSettings.effects||(typeof matchMedia==='function'&&matchMedia('(prefers-reduced-motion: reduce)').matches))skipGachaReveal();}}}
}
function renderWeapons(){
 const root=$('#inventory-weapons');if(!root)return;const state=collectionState;
 root.innerHTML=state&&Object.keys(state.weapons).length?Object.keys(state.weapons).map(id=>{const w=GACHA_DATA.weapons[id],owner=Object.keys(state.equipment).find(h=>state.equipment[h]===id);return '<article class="weapon-card"><span class="weapon-mini">'+w.icon+'</span><div><b>'+'★'.repeat(w.stars)+' '+gachaLoc(w.name)+'</b><p>'+tr('weaponBonus',w)+'</p><select '+(mode==='fight'?'disabled':'')+' aria-label="'+tr('equipWeapon')+'" data-equip="'+id+'"><option value="">'+tr('unequipWeapon')+'</option>'+state.heroes.map(h=>'<option value="'+h+'" '+(owner===h?'selected':'')+'>'+heroText(def(h)).name+'</option>').join('')+'</select></div></article>';}).join(''):'<p>'+tr('weaponEmpty')+'</p>';
}
function initGacha(){
 $('#gacha-open').onclick=openGacha;$('#draw-1').onclick=()=>performDraw(1);$('#draw-10').onclick=()=>performDraw(10);
 $('#gacha-tabs').onclick=e=>{const b=e.target.closest('[data-banner]');if(b&&!b.disabled){resetGachaPresentation();gachaBanner=b.dataset.banner;gachaResults=[];gachaError='';renderGacha();}};
 $('#gacha-result-close').onclick=()=>{resetGachaPresentation();gachaResults=[];renderGacha();$('#draw-10').focus();};
 $('#gacha-reveal-next').onclick=advanceGachaReveal;$('#gacha-reveal-card').onclick=advanceGachaReveal;$('#gacha-reveal-skip').onclick=skipGachaReveal;
 $('#gacha-results').onclick=e=>{const card=e.target.closest('[data-card-index]');if(card&&gachaResults[+card.dataset.cardIndex])openCardArtwork(gachaResults[+card.dataset.cardIndex],card);};
 $('#gacha-gallery-open').onclick=()=>{const banner=GACHA_DATA.banners.find(b=>b.id===gachaBanner),id=banner.kind==='character'?banner.featured:'moon';openCardArtwork({kind:'character',id,stars:CHARACTER_DESIGNS[id].stars},$('#gacha-gallery-open'));};
 $('#gacha-gallery-list').onclick=e=>{const b=e.target.closest('[data-gallery-id]');if(b){const id=b.dataset.galleryId;gachaInspectItem={kind:'character',id,stars:CHARACTER_DESIGNS[id].stars};renderCardArtwork();$('#gacha-gallery-list [data-gallery-id="'+id+'"]').focus();}};$('#gacha-art-close').onclick=closeCardArtwork;
 $('#gacha-dialog').addEventListener('cancel',e=>{if(gachaInspectItem){e.preventDefault();closeCardArtwork();}else if(gachaResults.length){e.preventDefault();if(gachaRevealPhase!=='overview')skipGachaReveal();else {resetGachaPresentation();gachaResults=[];renderGacha();}}});
 $('#gacha-dialog').addEventListener('close',()=>{if(!$('#gacha-dialog').open){gachaResults=[];resetGachaPresentation();}});
 $('#gacha-exchange').onclick=async()=>{if(gachaBusy||!accountUser)return;const context=collectionContext();gachaBusy=true;gachaError='';renderGacha();try{await flushAccountSave();if(!context.current())return;const data=await accountApi('exchange','POST',{});if(context.current())setCollection(data.collection);}catch(e){if(context.current())gachaError=e.message;}finally{if(context.current()){gachaBusy=false;renderGacha();}}};
 $('#inventory-weapons').onchange=async e=>{const select=e.target.closest('[data-equip]');if(!select||mode==='fight'||!accountUser)return;const context=collectionContext();select.disabled=true;try{await flushAccountSave();if(!context.current())return;const weapon=select.dataset.equip,hero=select.value||Object.keys(collectionState.equipment).find(h=>collectionState.equipment[h]===weapon);const data=await accountApi('equip','POST',{hero,weapon:select.value?weapon:null});if(!context.current())return;setCollection(data.collection);prepare();$('#weapon-error').textContent='';}catch(error){if(context.current())$('#weapon-error').textContent=accountErrorMessage(error.message);}finally{if(context.current())renderWeapons();}};
}
