'use strict';
// Language-independent combat data; changing the locale never resets a battle.
const TEXT = {
appearanceCount:['已拥有外观：{n}','Appearances owned: {n}','所持している外見：{n}'],
brand:['远境传说','Wilds & Wonders','遠境の物語'],lobby:['待机大厅','Camp','待機ロビー'],adventure:['冒险旅程','Expedition','冒険の旅'],help:['玩法指南 ↗','How to play ↗','遊び方 ↗'],
campEyebrow:['星灯营地 · 旅途的起点','STARLIGHT CAMP · A PLACE TO BEGIN','星灯りのキャンプ · 旅のはじまり'],campTitle:['星灯未灭，旅人归来。','A light to come home to.','星灯りのもとへ、おかえり。'],campSubtitle:['歇一歇，与你的伙伴一起，等待下一次出发。','Rest with your companions before your next journey.','仲間たちとひと休み。次の冒険は、ここから。'],campSafe:['营地安全','Camp secure','キャンプは平穏'],onDisplay:['大厅展示角色','Featured companion','ロビーの仲間'],appearance:['当前外观','Appearance','外見'],baseSkin:['旅途原装','Traveler’s attire','旅の装い'],appearanceNote:['当前已拥有 1 款外观','1 appearance owned','所持している外見：1'],chapterOne:['第一章 · 晨星的回响','CHAPTER I · ECHOES OF THE MORNING STAR','第一章 · 明けの星の残響'],campaignTitle:['找回失落的晨星','The Lost Morning Star','失われた明けの星'],campaignSynopsis:['守护远境的晨星碎裂，黑雾令昔日守护者迷失。带领八位旅伴，循着星屑穿过林地、遗迹与余烬，寻找黑雾背后的真相。','The Morning Star has shattered. Black mist has possessed the realm’s guardians. Lead eight companions through woods, ruins and embers to uncover the truth.','遠境を守る明けの星が砕け、黒い霧が守護者たちの心を奪った。八人の仲間と森、遺跡、残り火の向こうへ。星の欠片をたどり、霧の真実を探そう。'],nextDestination:['下一处目的地','Next destination','次の目的地'],depart:['启程冒险 →','Begin expedition →','冒険に出発 →'],resumeJourney:['继续旅程 →','Continue journey →','旅を続ける →'],returnBattle:['返回战场 →','Return to battle →','戦場に戻る →'],revisit:['重访远境 →','Revisit the realm →','遠境を再訪する →'],journal:['旅途手记','Travel journal','旅の手記'],journalHint:['重读已抵达关卡的故事。通关后解锁战后篇章。','Revisit places you have reached. Victories unlock their aftermath.','訪れた場所の物語を読み返せます。勝利すると戦いの後の物語が解放されます。'],companionProfile:['展示角色档案','Companion profile','展示中の仲間'],collection:['我的棋子收藏','Your companions','所持している仲間'],collectionHint:['点击棋子设为大厅展示角色。展示选择不会改变出战阵容。','Select a companion to feature in camp. Your battle lineup stays the same.','仲間を選ぶとロビーに展示します。出撃編成は変わりません。'],ownedCount:['已拥有 {n} / {n}','{n} / {n} owned','所持 {n} / {n}'],displayed:['展示中','Featured','展示中'],owned:['已拥有','Owned','所持済み'],
adventureTitle:['向未知之境进发。','Into the unknown.','未知の遠境へ。'],adventureSubtitle:['集结伙伴，巧妙布阵。让每一种羁绊，成为冒险的力量。','Gather companions. Shape your formation. Let your bonds lead the way.','仲間を集め、陣形を整えよう。絆が冒険の力になる。'],adventureProgress:['冒险进度','Journey progress','冒険の進行'],readStory:['回顾剧情','Read story','物語を読む'],teamTraits:['队伍羁绊','Team bonds','チームの絆'],traitHint:['不同英雄的羁绊可叠加激活','Bonds count distinct companions.','異なる仲間で絆を発動。'],noteTitle:['✦ 冒险者笔记','✦ Traveler’s note','✦ 冒険者のメモ'],noteText:['守卫顶住前线，游侠从后方输出。别忘了带上一位能治愈伙伴的旅者。','Let guardians hold the front and rangers attack from behind. Remember a healer.','守護者は前衛、狩人は後衛へ。癒やし手も忘れずに。'],speed:['切换战斗速度','Toggle battle speed','戦闘速度を切り替え'],boardAria:['八列六行战场，可拖动蓝方棋子布阵','Eight-column, six-row battlefield. Drag allied pieces to deploy.','8列6行の戦場。味方をドラッグして配置。'],allies:['我方阵地','Allied ground','味方陣地'],enemies:['敌方阵地','Enemy ground','敵陣地'],deployed:['出战英雄','deployed','出撃中'],reset:['重置阵容','Reset lineup','編成リセット'],start:['开始战斗 →','Begin battle →','戦闘開始 →'],heroProfile:['英雄档案','Hero profile','仲間の詳細'],combatLog:['战斗记录','Battle log','戦闘ログ'],live:['实时','LIVE','記録'],yourTeam:['你的冒险小队','Your adventuring party','冒険のパーティー'],rosterHint:['点击卡片查看英雄 · 点击「上阵」加入战场，最多出战 5 人','Select a card for details. Deploy up to 5 companions.','カードで詳細を確認。「出撃」で最大5人まで編成。'],rosterCount:['8 位英雄 / 4 类技能','8 heroes / 4 skill types','8人の仲間 / 4種のスキル'],footer:['每一场冒险，都从一次相遇开始。','Every adventure begins with a meeting.','すべての冒険は、出会いから始まる。'],autoSave:['语言 · 角色 · 进度 自动保存','Preferences & progress saved locally','言語・仲間・進行状況を自動保存'],storageWarning:['本地存储不可用，本次进度无法保存。','Local storage is unavailable. This session cannot be saved.','ローカル保存を利用できません。今回の進行状況は保存されません。'],
guideTitle:['你的第一场远境冒险','Your first expedition','はじめての遠境の旅'],guide1:['从 8 位英雄中选出最多 5 人，在棋盘下半区拖动布阵。点「开始战斗」后，英雄会自动寻敌、移动、攻击。','Choose up to 5 of 8 heroes and drag them onto the lower half of the board. Begin battle to move, target and attack automatically.','8人から最大5人を選び、盤面の下半分にドラッグして配置。「戦闘開始」で索敵・移動・攻撃が自動で行われます。'],guide2:['每次普攻回复 25 点法力；满 100 点自动施放技能。蓝条是法力，绿条是生命，金色外环代表护盾。','Each basic attack restores 25 mana. At 100 mana, a skill casts automatically. Blue bars show mana, green bars health, and gold rings shields.','通常攻撃でマナが25回復し、100でスキルを発動。青いバーはマナ、緑はHP、金の輪はシールドです。'],guide3:['相同羁绊达到 2 / 3 名不同英雄时激活加成。搭配伤害、治疗、范围伤害与护盾四类技能。','Deploy 2 or 3 different heroes sharing a bond to activate bonuses. Combine damage, healing, area damage and shields.','同じ絆を持つ異なる仲間が2人・3人で効果が発動。単体攻撃・回復・範囲攻撃・シールドを組み合わせましょう。'],guide4:['每关恢复全队状态。阅读剧情，击败远古石王。回大厅会暂停战斗；关闭程序后从当前关卡备战重新开始。语言、展示角色、阵容和通关进度自动保存。','Each stage restores your party. Follow the story to the Stone King. Camp pauses battle; reopening the app restarts the current stage in preparation. Language, featured hero, lineup and progress are saved.','各ステージで全員が回復。物語を進め、石王を倒しましょう。ロビーでは戦闘が一時停止。再起動時は現在のステージの準備から再開。言語・展示する仲間・編成・クリア状況を保存します。'],gotIt:['明白了 →','Got it →','わかった →'],close:['关闭','Close','閉じる'],
prep:['● 准备布阵','● Preparing','● 配置準備'],fighting:['● 战斗进行中','● In battle','● 戦闘中'],paused:['● 战斗暂停','● Battle paused','● 一時停止中'],winPhase:['✦ 探索成功','✦ Victory','✦ 探索成功'],losePhase:['● 队伍已倒下','● Party defeated','● パーティー敗北'],pause:['暂停','Pause','一時停止'],resume:['继续','Resume','再開'],prepHint:['拖动英雄调整站位 · 仅可部署在下半区','Drag heroes to the lower half','下半分にドラッグして配置'],fightHint:['普攻回蓝 · 满蓝自动施法','Attack for mana · Auto-cast when full','通常攻撃でマナ回復 · 満タンで発動'],explore:['探索关卡','EXPLORE','探索'],bossLabel:['最终决战','BOSS','最終決戦'],activeTraits:['{n} 激活','{n} active','{n} 発動中'],inspect:['查看 {name}','Inspect {name}','{name}の詳細'],onTeam:['● 已上阵','● Deployed','● 出撃中'],remove:['撤下 −','Remove −','外す −'],deploy:['上阵 +','Deploy +','出撃 +'],hp:['基础生命','Base HP','基本HP'],atk:['攻击力','Attack','攻撃力'],range:['攻击距离','Range','射程'],cells:['{n} 格','{n} tiles','{n} マス'],mana:['100 法力','100 mana','100 マナ'],manaHint:['每次普攻 +25 法力 · 羁绊对双方各自生效','+25 mana per attack · Bonds apply per team','通常攻撃でマナ+25 · 絆は陣営ごとに発動'],readyLog:['整装待发，选择你的冒险阵容。','Ready for the journey. Choose your party.','旅の準備を整え、仲間を選ぼう。'],startLog:['战斗开始！','Battle begins!','戦闘開始！'],fallenLog:['{name} 倒下了','{name} has fallen.','{name}が倒れた。'],castLog:['{name} 施放「{skill}」','{name} casts {skill}.','{name}が「{skill}」を発動。'],shieldFloat:['盾 +{n}','Shield +{n}','盾 +{n}'],winLog:['战斗胜利！新的故事正在展开。','Victory! The story continues.','勝利！物語は続いていく。'],timeoutLog:['战斗超时，请调整阵容后重试。','Time is up. Regroup and try again.','時間切れ。編成して再挑戦しよう。'],loseLog:['冒险暂歇，调整阵容再试一次。','A moment to regroup. Try again.','旅はひと休み。編成して再挑戦しよう。'],victory:['胜利，前路已开启','Victory opens the way','勝利が道を開いた'],finalVictory:['远境，因你而苏醒','The realm awakens','遠境が目を覚ます'],timeoutTitle:['暂时陷入僵局','A temporary stalemate','決着は持ち越し'],defeat:['旅途尚未结束','The journey is not over','旅はまだ終わらない'],clearSummary:['{stage}已通关 · 存活 {n} 人','{stage} cleared · {n} survivors','{stage}クリア · 生存 {n} 人'],defeatSummary:['调整站位与羁绊，再次迎接挑战。','Adjust your formation and bonds, then try again.','配置と絆を見直して、もう一度挑もう。'],battleTime:['战斗用时 {time}','Battle time {time}','戦闘時間 {time}'],continueStory:['继续剧情 →','Continue story →','物語の続きへ →'],retry:['调整阵容并重试 ↻','Regroup and retry ↻','編成して再挑戦 ↻'],objective:['本关目标','OBJECTIVE','今回の目標'],beforeBattle:['战前 · {n} / 5','BEFORE BATTLE · {n} / 5','戦いの前 · {n} / 5'],afterBattle:['战后 · {n} / 5','AFTERMATH · {n} / 5','戦いの後 · {n} / 5'],prepareAction:['进入布阵 →','Prepare your party →','編成へ →'],nextChapter:['前往下一章 →','Next chapter →','次の章へ →'],backCamp:['返回星灯营地 →','Return to camp →','星灯りのキャンプへ →'],completed:['晨星已归位 · 故事已完成','The star is restored · Story complete','星は還った · 物語クリア'],clearedCount:['已通关 {n} / 5','{n} / 5 stages cleared','クリア {n} / 5'],beforeLabel:['战前故事','Before battle','戦いの前'],afterLabel:['战后故事','After battle','戦いの後'],locked:['尚未抵达','Not reached','未到達'],read:['阅读','Read','読む']
};
const HERO_TEXT={
oak:[['Oak Guardian','Frontline · Shield','Ancient Embrace','Grants 200 shield to self and the two nearest allies.','“As long as my roots hold, no companion falls alone.”'],['樫の守護者','前衛 · シールド','古樹の抱擁','自身と最も近い味方2人に200のシールドを付与する。','「根を張るかぎり、仲間を独りにはしない。」']],
arrow:[['Windstrider','Backline · Damage','Piercing Arrow','Deals 250 damage to the nearest enemy.','“The wind remembers every path home.”'],['風追いの狩人','後衛 · 単体攻撃','木立を貫く矢','最も近い敵に250のダメージを与える。','「風は、帰り道を覚えている。」']],
ember:[['Ember Mage','Backline · Area damage','Meteor Shower','Deals 185 damage to the target and enemies within one tile.','“A small ember can challenge the night.”'],['残火の魔術師','後衛 · 範囲攻撃','流星の火雨','対象と周囲1マスの敵に185のダメージを与える。','「小さな火でも、夜に立ち向かえる。」']],
sage:[['Mosslight Healer','Backline · Healing','Seed of Renewal','Heals the ally with the lowest health ratio for 280 and adjacent allies for 140.','“Even wounded earth remembers how to bloom.”'],['苔光の癒やし手','後衛 · 回復','再生の芽','HP割合が最も低い味方を280、隣接する味方を140回復する。','「傷ついた大地も、咲き方を忘れない。」']],
knight:[['Dawn Knight','Frontline · Damage','Daybreak Cleave','Deals 230 damage to the nearest enemy.','“My oath belongs to the living, not a throne.”'],['暁の騎士','前衛 · 単体攻撃','夜明けの一閃','最も近い敵に230のダメージを与える。','「この誓いは、王座ではなく命のために。」']],
frost:[['Frost Whisperer','Backline · Area damage','Crystal Field','Deals 170 damage to the target and enemies within one tile.','“There is a heartbeat beneath the ice.”'],['霜語りの術師','後衛 · 範囲攻撃','氷晶の領域','対象と周囲1マスの敵に170のダメージを与える。','「氷の下に、まだ鼓動がある。」']],
warden:[['Runestone Warden','Frontline · Shield','Runic Barrier','Grants 220 shield to self and the two nearest allies.','“Some promises outlast the stones that bear them.”'],['符石の番人','前衛 · シールド','ルーンの障壁','自身と最も近い味方2人に220のシールドを付与する。','「石が砕けても、約束は残る。」']],
moon:[['Moonshadow Hunter','Backline · Damage','Moonfall','Deals 290 damage to the nearest enemy.','“I walk in shadows so others can follow the stars.”'],['月影の狩人','後衛 · 単体攻撃','月墜ち','最も近い敵に290のダメージを与える。','「誰かが星を追えるよう、私は影を歩く。」']],
boss:[['Ancient Stone King','Final boss','Earthshatter','Deals 125 damage to every enemy.',''],['古の石王','最終ボス','大地の震動','敵全体に125のダメージを与える。','']]
};
const ZH_QUOTES={oak:'「只要根须还在，就没有谁需要独自承受风雨。」',arrow:'「风记得每一条归途。」',ember:'「一粒余烬，也能向长夜宣战。」',sage:'「受伤的大地，也记得如何开花。」',knight:'「我的誓言属于生者，而非王座。」',frost:'「听，冰层之下还有心跳。」',warden:'「有些约定，比镌刻它的石头更长久。」',moon:'「我行于暗处，好让伙伴追随星光。」'};
const TRAIT_TEXT={guard:[['Guardian','2 / 3: Team max HP +18% / +30%'],['守護','2 / 3人：全員の最大HP +18% / +30%']],wild:[['Woodland','2 / 3: Team heals 1% / 2% HP each second'],['森林','2 / 3人：全員が毎秒HPを1% / 2%回復']],ranger:[['Ranger','2 / 3: Team attack speed +20% / +35%'],['狩人','2 / 3人：全員の攻撃速度 +20% / +35%']],arcane:[['Arcane','2 / 3: Team skill power +25% / +45%'],['秘術','2 / 3人：全員のスキル威力 +25% / +45%']],dawn:[['Dawn','2 / 3: Team starts with 100 / 180 shield'],['暁光','2 / 3人：開始時、全員に100 / 180の盾']]};
const STAGE_TEXT=[['Whispering Woods','ささやきの森'],['Forgotten Pass','忘却の峠'],['Moonlit Ruins','月影の遺跡'],['Ember Gate','残火の門'],['Ancient Throne','古の王座']];
let language='zh';
function tr(key,params={}){const entry=TEXT[key];if(!entry)throw new Error('Missing translation: '+key);if(key==='cells'&&language==='en'&&params.n===1)return '1 tile';return entry[{zh:0,en:1,ja:2}[language]].replace(/\{(\w+)\}/g,(_,k)=>params[k]??'{'+k+'}');}
function heroText(h){if(language==='zh')return {...h,quote:ZH_QUOTES[h.id]||''};const [name,role,skill,desc,quote]=HERO_TEXT[h.id][language==='en'?0:1];return {...h,name,role,skill,desc,quote};}
function traitText(key){const original=TRAITS[key];if(language==='zh')return original;const [name,desc]=TRAIT_TEXT[key][language==='en'?0:1];return {...original,name,desc};}
function stageName(i){return language==='zh'?STAGES[i].name:STAGE_TEXT[i][language==='en'?0:1];}
function localizePage(){document.documentElement.lang=language==='zh'?'zh-CN':language;document.title=tr('brand');document.querySelectorAll('[data-i18n]').forEach(e=>e.textContent=tr(e.dataset.i18n));document.querySelectorAll('[data-i18n-aria]').forEach(e=>e.setAttribute('aria-label',tr(e.dataset.i18nAria)));document.querySelectorAll('[data-i18n-title]').forEach(e=>e.title=tr(e.dataset.i18nTitle));document.querySelector('#language').value=language;document.querySelector('#story-language').value=language;}
