'use strict';
// Original serialized campaign. Each scene states why this encounter is expedition or defense.
const STORY={zh:[
{speaker:'arrow',goal:'外出冒险：在雨夜站台击退拦截者，夺回写着你名字的黑色信箱。',before:{title:'01 / 雨夜里迟到的列车',text:'你一直以为梦中的赤色海面只是失眠的副作用，直到一封没有寄件人的录取通知，把你带到凌晨两点的临海车站。列车没有乘客，只有一只刻着你名字的黑色信箱。戴耳机的女孩自称“逐风”，说晨星观测局正在招收能听见龙鸣的人。话音未落，站台上的影子逆着灯光站了起来。',line:'先别问学费。我们活着离开这里，你再决定要不要相信我。'},after:{title:'不是录取，是求救',text:'拦截者化作潮湿的灰。信箱里不是入学资料，而是一张十年前的合照：失踪的父亲站在观测局门前，胸口挂着与你一模一样的晶体。录音只有六个字：“别让钟声响起。”逐风关闭耳机，第一次没有开玩笑。',line:'这封信一直在等你。可发信人，十年前就已经不在名单上了。'}},
{speaker:'knight',goal:'据点防守：守住观测站核心，抵挡三波来袭者，等档案解密完成。',before:{title:'02 / 欢迎宴在警报中结束',text:'晨星观测局藏在旧天文馆下面。所谓八名英雄，是八个背负异常血脉的年轻人使用的行动代号。欢迎宴只有泡面和一份还没签名的保密协议。凌晨三点，海雾穿过封锁线，警报同时点亮了所有走廊。有人用你的血样坐标打开了门。骑士把解密终端推到你身后，命令队伍就地守住通路。',line:'今晚没有新生和前辈。路口交给我们，核心交给你。'},after:{title:'白名单上的陌生人',text:'最后一波袭击在防线前停下，核心完成了解密。十年前，观测局曾把一位古老生命封在海底钟楼，而“晨星”不是武器，是防止封印吞噬守望者的共鸣装置。现在，装置正被远程唤醒。发送指令的权限，来自你父亲仍然有效的工号。',line:'死人的权限不会自己醒来。有人要我们去看那座沉没的档案馆。'}},
{speaker:'frost',goal:'外出冒险：潜入沉没档案馆，击败记忆拟态，取得关闭钟楼的密钥。',before:{title:'03 / 水下的毕业照',text:'你们沿废弃地铁线进入海下档案馆。玻璃后漂浮着一届从未毕业的学员照片，每张脸都停在十八岁。霜语发现，馆内守卫是由龙血记忆复制的拟态，甚至会使用同伴的技能。父亲留下的密钥在最深处，但你越接近它，耳边的龙鸣就越像自己的声音。',line:'看到熟悉的脸也不要停下。记忆会骗人，而现在握着你的手的人不会。'},after:{title:'被删掉的第九个名字',text:'密钥打开了一段未删净的录像：父亲没有死在事故里，而是成为封印的“第九位守望者”。观测局把他的名字从历史中抹去，以为沉默就能阻止下一次失控。你本可以打开封印，把他接回来；代价却是整座海岸城市。录像结束前，他望向镜头，像早知道你会看到这里。',line:'血脉只告诉你门在哪里。要不要打开，是你的选择。'}},
{speaker:'sage',goal:'据点防守：保护撤离枢纽与平民车队，抵挡四波进攻，保持核心不被摧毁。',before:{title:'04 / 把黎明留给他们',text:'海底钟楼开始预热，城市的潮位在没有月亮的夜里不断升高。最后一班撤离车队停在旧高架桥，医疗组需要时间重启枢纽。黑潮从封锁口涌来，正沿唯一的撤离道路追赶平民。你收到钟楼的单独邀请，却把耳机摘下，站回同伴身边。',line:'有人想让你做传说里的主角。现在，先帮我守住这些普通人的明天。'},after:{title:'没有人留下名字',text:'最后一辆巴士驶离桥面，车窗里有人画了一颗歪歪扭扭的星。没有镜头，也没有喝彩，只有八个人靠着路障分一瓶已经温了的水。密钥发出最后一次提示：钟楼还能关闭，但必须有人进入它的共鸣中心。所有人都听见了。没有人后退。',line:'去吧。我们不是来替你选择的，我们是来陪你承担选择的。'}},
{speaker:'warden',goal:'外出冒险：进入海底钟楼，击败封印守壳与近卫，在共鸣完成前阻止钟声。',before:{title:'05 / 钟声响起之前',text:'钟楼内部没有海水，只有一片倒悬的星空。你父亲的声音从石质巨像中传来，温柔地许诺一个没人失去过家人的世界。符石守望却发现，那只是古老生命借他的记忆发出的诱惑。巨像的胸口，就是封印与龙血意识交汇的中心。八枚行动徽章依次点亮，你第一次主动回应了身体里的龙鸣。',line:'我们不需要一个完美的假世界。真实的世界很糟，但我们的朋友都在这里。'},after:{title:'第一章终 / 未寄出的回信',text:'巨像碎裂时，你只来得及看见父亲真正的眼睛。他没有要求你拯救他，只轻轻点了点头。你们关闭了钟楼，把最后一段记忆带回星灯营地。清晨的海面恢复蓝色，你在空白录取通知上写下名字。当天夜里，远方另一座城市的钟，提前走快了一秒。',line:'第一封信已经收到。下一次，我们一起回信。'}}
],en:[
{speaker:'arrow',goal:'Expedition: defeat the station interceptors and recover the black case bearing your name.',before:{title:'01 / The Train After Midnight',text:'You thought the red ocean in your dreams was only insomnia. Then an unsigned admission letter led you to a coastal station at two in the morning. An empty train carries a black case with your name. A girl calling herself Windstrider says Morningstar recruits people who hear dragons. The shadows on the platform rise against the light.',line:'Ask about tuition later. First we get out alive; then you decide whether to trust me.'},after:{title:'A Call for Help',text:'The interceptors turn to wet ash. Inside the case is a ten-year-old photo of your missing father outside Morningstar, wearing the same crystal as you. A recording says, “Do not let the bell ring.” For once, Windstrider stops joking.',line:'This letter has been waiting for you. But its sender vanished from our records ten years ago.'}},
{speaker:'knight',goal:'Base defense: hold the observatory core against three waves while the archive decrypts.',before:{title:'02 / A Welcome Interrupted',text:'Morningstar hides beneath an abandoned planetarium. Its eight heroes are young people with unusual bloodlines, using field aliases. Your welcome dinner is instant noodles and an unsigned secrecy form. At three, sea mist breaches the perimeter. Someone used your blood sample as a key. The knight sets the terminal behind you and orders the team to hold the road.',line:'No rookies or veterans tonight. We hold the junctions. You protect the core.'},after:{title:'A Name on the Allowlist',text:'The final attackers fall and decryption completes. Ten years ago, Morningstar sealed an ancient being in a submerged belfry. Its resonance device was meant to protect the watcher inside. Now someone is waking it remotely, using your father’s still-valid staff credentials.',line:'A dead man’s credentials do not wake themselves. Someone wants us to visit the drowned archive.'}},
{speaker:'frost',goal:'Expedition: enter the drowned archive, defeat memory mimics and retrieve the belfry shutdown key.',before:{title:'03 / Photographs Underwater',text:'A disused subway leads beneath the sea. Behind glass drift photographs of students who never graduated, every face forever eighteen. Frost discovers guardians copied from draconic memories. They even imitate your companions’ skills. The deeper you go, the more the dragon’s voice sounds like your own.',line:'Do not stop for a familiar face. Memories can lie. The hand holding yours is here, now.'},after:{title:'The Ninth Name',text:'The key unlocks an erased recording. Your father survived the accident as the seal’s ninth watcher. Morningstar removed his name, hoping silence would prevent another disaster. You could open the seal and bring him back, at the cost of the coast. Before the recording ends, he looks into the camera.',line:'Your blood can show you the door. Only you choose whether to open it.'}},
{speaker:'sage',goal:'Base defense: protect the evacuation hub from four waves and keep its core intact.',before:{title:'04 / Leave Them the Dawn',text:'The belfry begins to wake. The tide rises without a moon. The last evacuation convoy waits beneath an old overpass while medics restart its hub. Black mist pours along the only escape route. A private invitation arrives from the belfry. You take off your headset and return to your companions.',line:'Someone wants you to become a legend. First, help me protect an ordinary tomorrow.'},after:{title:'No Names Recorded',text:'The final bus leaves the bridge. A child draws a crooked star on its window. No cameras, no applause: eight exhausted people share warm water behind a barricade. The key gives one last warning. Someone must enter the resonance chamber to stop the bell. Everyone hears it. No one steps back.',line:'We are not here to make your choice. We are here to share its weight.'}},
{speaker:'warden',goal:'Expedition: defeat the seal-shell and its guard before the belfry completes its resonance.',before:{title:'05 / Before the Bell',text:'Inside the belfry is an inverted sky. Your father’s voice speaks from a stone giant, offering a world where no family was ever lost. The Warden recognizes the ancient being borrowing his memories. The giant’s heart joins the seal to the draconic mind. Eight field badges light in turn. At last, you answer the voice in your blood.',line:'We do not need a perfect imitation. The real world is flawed, but our friends are in it.'},after:{title:'CHAPTER I / An Unsent Reply',text:'As the shell breaks, you glimpse your father’s real eyes. He does not ask to be rescued. He simply nods. You close the belfry and carry his last memory back to camp. At dawn the sea is blue. You sign the blank admission letter. That night, in a distant city, another clock moves one second ahead.',line:'The first letter has arrived. Next time, we reply together.'}}
],ja:[
{speaker:'arrow',goal:'出征：雨の駅で迎撃部隊を倒し、あなたの名が刻まれた黒いケースを回収する。',before:{title:'01 / 真夜中の遅延列車',text:'夢の赤い海は不眠のせいだと思っていた。差出人のない入学通知に導かれ、午前二時の海辺の駅へ。無人列車には自分の名が刻まれたケースがある。「風追い」と名乗る少女は、モーニングスターが竜の声を聞く者を探していると言った。その瞬間、ホームの影が光に逆らって立ち上がった。',line:'学費の話は後。まず生きて出てから、私を信じるか決めて。'},after:{title:'招待ではなく救難信号',text:'敵は濡れた灰になった。ケースの中には十年前の写真。行方不明の父が、あなたと同じ結晶を胸に観測局の前に立っている。録音には「鐘を鳴らすな」。少女は初めて冗談をやめた。',line:'この手紙はあなたを待っていた。でも差出人は、十年前に記録から消えている。'}},
{speaker:'knight',goal:'拠点防衛：記録の解読が終わるまで、三波の襲撃から観測所コアを守る。',before:{title:'02 / 警報で終わる歓迎会',text:'観測局は古いプラネタリウムの地下にあった。八人の英雄とは、異常な血を持つ若者たちの作戦名。歓迎会はカップ麺と未署名の誓約書だけ。午前三時、海霧が防衛線を越えた。誰かがあなたの血液試料を鍵に使ったのだ。騎士は端末を背後に置き、道路の防衛を命じた。',line:'今夜は新人も先輩もない。交差点は任せろ。君はコアを守れ。'},after:{title:'消されなかった権限',text:'最後の敵が倒れ、解読が終わる。十年前、局は古代の存在を海底の鐘楼に封印した。共鳴装置は内部の番人を守るためのものだった。今、それを遠隔起動しているのは、まだ有効な父の職員番号だった。',line:'死者の権限は勝手に動かない。誰かが水没した記録館へ誘っている。'}},
{speaker:'frost',goal:'出征：沈んだ記録館の記憶擬態を倒し、鐘楼を止める鍵を手に入れる。',before:{title:'03 / 水底の卒業写真',text:'廃線を通って海底の記録館へ。ガラスの奥には、卒業できなかった生徒の写真が漂う。誰もが十八歳のままだった。守衛は竜血の記憶が作った擬態で、仲間の技までまねる。深部へ進むほど、竜の声が自分の声に似て聞こえた。',line:'見覚えのある顔でも止まらないで。記憶は嘘をつく。でも今つないだ手は、ここにある。'},after:{title:'九番目の名前',text:'鍵は消された映像を開いた。父は事故で死なず、封印の九番目の番人になっていた。局は次の災厄を恐れ、その名前を歴史から消した。封印を開けば父は戻る。代わりに海辺の街が失われる。映像の最後、父はカメラを見つめた。',line:'血は扉の場所を教えるだけ。開くかどうかは、あなたが決める。'}},
{speaker:'sage',goal:'拠点防衛：避難拠点を四波の襲撃から守り、コアを維持する。',before:{title:'04 / あの人たちに夜明けを',text:'鐘楼が目覚め始め、月のない夜に潮位が上がり続ける。最後の避難車列は古い高架下で医療班の再起動を待っていた。黒い潮が唯一の避難路を追ってくる。鐘楼から個人的な招待が届いたが、あなたはイヤホンを外し、仲間の隣に戻った。',line:'誰かは君を伝説の主人公にしたいみたい。今は、普通の人たちの明日を守ろう。'},after:{title:'名前の残らない勝利',text:'最後のバスが橋を渡る。窓には子供の描いた不格好な星。拍手もカメラもない。八人はバリケードにもたれ、ぬるい水を分け合った。鍵が最後の警告を鳴らす。鐘を止めるには共鳴室へ入る必要がある。全員が聞いた。誰も下がらなかった。',line:'選択を代わりにするためじゃない。その重さを、一緒に背負うために来たんだ。'}},
{speaker:'warden',goal:'出征：封印の石殻と近衛を倒し、共鳴が完成する前に鐘を止める。',before:{title:'05 / 鐘が鳴る前に',text:'鐘楼の中には逆さの星空があった。石の巨像から父の声が聞こえ、家族を失わなかった世界を約束する。番人は、それが父の記憶を借りた誘惑だと見抜いた。巨像の胸が封印と竜の意識の交点。八つの徽章が順に光り、あなたは初めて自ら血の声に答えた。',line:'完璧な偽物はいらない。現実は不格好でも、友達はここにいる。'},after:{title:'第一章・終 / まだ出していない返事',text:'石殻が砕けた瞬間、本当の父の瞳が見えた。助けを求めず、ただ小さくうなずいた。鐘楼を止め、最後の記憶をキャンプへ持ち帰る。朝の海は青く、あなたは白紙の入学通知に名前を書いた。その夜、遠い街の時計が一秒だけ先に進んだ。',line:'最初の手紙は届いた。次は、一緒に返事を出そう。'}}
]};
function chapterText(index){return STORY[language][index];}
