'use strict';
// A chapter has a tactical objective plus a before/after scene. Speakers are hero IDs.
const STORY={
zh:[
{speaker:'sage',goal:'击退被黑雾侵蚀的林地守卫，取回第一枚星屑。',before:{title:'第一盏熄灭的灯',text:'昨夜，守护远境的晨星裂成碎片。星灯营地外，归巢的鸟不再鸣叫，熟悉的守卫却把武器指向了旅人。苔光医师从一片焦黑的叶脉里，看见了仍在闪烁的星屑。八位旅伴决定沿着它微弱的光，寻找长夜的源头。',line:'他们不是我们的敌人，是黑雾困住了他们。打散雾影，把他们带回家。'},after:{title:'叶脉里的星图',text:'守卫眼中的黑色褪去，一枚温热的星屑落进你的掌心。它投出一条通往遗忘隘口的光路。医师留下一盏草药灯，昏睡的守卫终于恢复了平稳的呼吸。',line:'星光还活着。下一枚碎片在山口——我们来得及。'}},
{speaker:'knight',goal:'突破隘口守军的阵线，唤醒通往遗迹的石桥。',before:{title:'不再认识归人的哨所',text:'遗忘隘口的石桥停在半空。曙光骑士认出了桥头的纹章：那是他曾立誓守护的哨所。如今，受侵蚀的骑士与符石傀儡结成盾墙，拒绝所有带着星光的人经过。',line:'我曾发誓守住这里。今天，我要守住的是桥另一边的人。'},after:{title:'誓言的另一边',text:'盾墙散开，桥心的第二枚星屑被唤醒。石桥重新合拢，露出古老刻字：“晨星不是王的冠冕，是众人的约定。”桥另一端，月影遗迹亮起一圈淡蓝色的光。',line:'王座曾经保护我们。若它已忘记誓言，就由我们去提醒它。'}},
{speaker:'frost',goal:'驱散遗迹里的镜像守卫，读出封存在星屑中的记忆。',before:{title:'月光保存的记忆',text:'月影遗迹的水面映出并不存在的天空。黑雾借月光塑造出旅伴们的镜像，拦在祭坛四周。霜语术士发现，第三枚星屑里封着石王最后一次清醒时的记忆。只有击碎镜像，记忆才会解冻。',line:'别被相同的面容骗了。它们会模仿力量，却不懂伙伴为何并肩。'},after:{title:'被误解的守护者',text:'冰晶中的画面展开：晨星坠落时，石王把黑雾封进自己的胸膛，独自坐回王座。漫长岁月里，囚笼终于裂开，他也失去了神志。造成长夜的，并不是一位暴君，而是一名不愿求救的守护者。',line:'这次，我们不是去讨伐一位王。我们去接回一位撑了太久的伙伴。'}},
{speaker:'ember',goal:'突破余烬之门，收集最后一枚散落的星屑。',before:{title:'给长夜的一点火',text:'王座前的余烬之门吞噬着所有靠近的光。最后一枚散落的星屑被困在炉心，黑雾化作昔日近卫守在火中。余烬法师举起营地带来的小灯，队伍的影子终于连成了一条路。',line:'我们不需要比黑夜更大的火。只要这一点光，能从一个人传到另一个人。'},after:{title:'八双手，一道光',text:'炉火由黑转金，四枚星屑在你们之间缓缓旋转。通向王座的门打开了。每个旅伴都伸出一只手，让星屑记住自己的温度；缺失的星心，就在石王胸口。',line:'别让他再一个人承受了。走吧，去把最后一盏灯点亮。'}},
{speaker:'warden',goal:'击败远古石王与其雾影近卫，解放星心。',before:{title:'王座之上的最后一人',text:'远古石王缓缓起身，碎裂的胸甲里涌出黑雾。他仍重复着最后的命令：“退后，我会守住。”符石守望听见了命令下的求救声。四枚星屑亮起，但只有击破受侵蚀的外壳，才能让星心重新回应。',line:'您的守望已经足够漫长。现在，让我们站在您身前。'},after:{title:'晨星不是一个人的光',text:'石甲崩落，星心与四枚碎片重聚。黑雾消散时，石王第一次放下了双手。远处林地重新响起鸟鸣，桥头的灯一盏盏点亮。你们回到星灯营地，给火堆添上新柴，也为那位沉默的守护者留了一个位置。',line:'这就是新的约定：没有人必须独自守望。明天的旅程，我们一起走。'}}
],
en:[
{speaker:'sage',goal:'Defeat the mist-bound woodland guardians and recover the first star shard.',before:{title:'The First Light Goes Out',text:'Last night, the Morning Star shattered. Beyond Starlight Camp, birds fell silent and familiar guardians turned their weapons on travelers. Inside a scorched leaf, the healer finds a shard still glowing. Eight companions follow its faint light toward the source of the long night.',line:'They are not our enemies. The mist has trapped them. Break its hold and bring them home.'},after:{title:'A Map in the Leaves',text:'The darkness fades from the guardians’ eyes. A warm star shard falls into your palm and projects a path toward Forgotten Pass. Beside a small herbal lantern, the sleeping guardians begin to breathe peacefully again.',line:'The starlight is still alive. Another shard waits at the pass. There is still time.'}},
{speaker:'knight',goal:'Break the defenders’ formation and restore the bridge to the ruins.',before:{title:'A Watchpost That Forgot',text:'The stone bridge at Forgotten Pass hangs in pieces. The Dawn Knight recognizes the crest of the post he once swore to protect. Now possessed knights and runestone constructs form a shield wall, refusing passage to anyone carrying starlight.',line:'I swore to defend this place. Today, I defend the people on the other side.'},after:{title:'Beyond the Oath',text:'The shield wall falls. A second shard awakens in the bridge, pulling the stones together. An inscription appears: “The Morning Star is no king’s crown. It is a promise shared by all.” Beyond the bridge, Moonlit Ruins glow pale blue.',line:'The throne once protected us. If it has forgotten its promise, we will remind it.'}},
{speaker:'frost',goal:'Dispel the mirror guardians and uncover the memory held in the shard.',before:{title:'Memories Kept by Moonlight',text:'The pools of Moonlit Ruins reflect a sky that does not exist. Mist shapes reflections of your companions around the altar. The Frost Whisperer senses the Stone King’s last lucid memory inside the third shard. Shatter the reflections, and the memory can thaw.',line:'Do not trust a familiar face. They can copy our power, but not the reason we stand together.'},after:{title:'The Guardian Misunderstood',text:'The memory unfolds: as the star fell, the Stone King sealed the mist inside his own chest and returned alone to his throne. Over the years, his prison cracked and his mind faded. The long night began with a guardian who never asked for help.',line:'We are not going to overthrow a king. We are going to bring home someone who stood watch too long.'}},
{speaker:'ember',goal:'Breach Ember Gate and recover the last scattered shard.',before:{title:'A Small Fire Against the Night',text:'Ember Gate swallows every approaching light. The last scattered shard is caught in its furnace, guarded by mist wearing the shapes of the old royal guard. The Ember Mage raises a little camp lantern. The party’s shadows join into a single path.',line:'Our fire need not be larger than the night. It only needs to pass from one person to the next.'},after:{title:'Eight Hands, One Light',text:'The furnace burns gold. Four star shards circle between you as the way to the throne opens. Every companion holds out a hand, letting the shards remember their warmth. The missing star heart is still inside the king’s chest.',line:'He does not have to carry it alone anymore. Let us light that final lamp.'}},
{speaker:'warden',goal:'Defeat the Ancient Stone King and his mist guard to free the star heart.',before:{title:'The Last Watcher',text:'The Stone King rises, black mist pouring through his fractured armor. He repeats his final command: “Stand back. I will hold.” Beneath it, the Runestone Warden hears a plea. The four shards shine, but his corrupted shell must break before the star heart can answer.',line:'You have watched over us long enough. Now let us stand in front of you.'},after:{title:'No One Shines Alone',text:'Stone armor falls away. The star heart joins the four shards, and the mist dissolves. For the first time, the king lowers his hands. Birds return to the woods; lamps awaken along the bridge. Back at camp, you add wood to the fire and leave a place for the quiet guardian.',line:'Here is our new promise: no one keeps watch alone. Tomorrow, we walk together.'}}
],
ja:[
{speaker:'sage',goal:'霧に囚われた森の守護者を倒し、最初の星の欠片を取り戻す。',before:{title:'最初に消えた灯り',text:'昨夜、遠境を守る明けの星が砕けた。キャンプの外では鳥の声が消え、見慣れた守護者が旅人に武器を向けている。癒やし手は焦げた葉の中に、まだ光る星の欠片を見つけた。八人の仲間はその光を頼りに、長い夜の源へと歩き出す。',line:'あの人たちは敵じゃない。霧に囚われているだけ。霧を払い、一緒に帰ろう。'},after:{title:'葉脈に浮かぶ星図',text:'守護者の瞳から闇が消え、温かな星の欠片が手のひらに落ちた。光は忘却の峠へ続く道を描き出す。薬草の灯りのそばで、眠る守護者たちの呼吸がようやく穏やかになった。',line:'星の光はまだ生きている。次の欠片は峠にある。まだ間に合うよ。'}},
{speaker:'knight',goal:'峠を守る部隊の陣形を崩し、遺跡へ続く石橋を蘇らせる。',before:{title:'帰る者を忘れた砦',text:'忘却の峠では、崩れた石橋が宙に止まっていた。暁の騎士は、かつて守ると誓った砦の紋章を見つける。今は霧に侵された騎士と符石の兵が盾の壁を作り、星の光を持つ者を拒んでいた。',line:'ここを守ると誓った。だが今日守るのは、橋の向こうにいる人々だ。'},after:{title:'誓いの向こう側',text:'盾の壁が崩れ、橋の中の二つ目の欠片が目を覚ます。石橋がつながり、古い文字が現れた。「明けの星は王の冠ではない。皆が交わした約束である。」橋の先で月影の遺跡が青く光った。',line:'王座はかつて私たちを守ってくれた。誓いを忘れたのなら、思い出してもらおう。'}},
{speaker:'frost',goal:'遺跡の幻影を払い、星の欠片に封じられた記憶を読み解く。',before:{title:'月光が守った記憶',text:'月影の遺跡の水面には、存在しない空が映っていた。霧は仲間たちの姿をまねて祭壇を囲む。霜語りの術師は三つ目の欠片に、石王が正気だった最後の記憶を感じた。幻影を砕けば、凍った記憶がほどける。',line:'同じ顔でも惑わされないで。力はまねできても、共に戦う理由まではまねできない。'},after:{title:'誤解された守護者',text:'記憶が映し出すのは、落ちる星と、霧を自らの胸に封じた石王だった。王は独りで王座に戻り、長い年月の末に封印も心も砕けてしまった。夜を招いたのは暴君ではなく、助けを求められなかった守護者だった。',line:'王を討ちに行くんじゃない。長く見張り続けた仲間を、迎えに行くの。'}},
{speaker:'ember',goal:'残火の門を突破し、最後の散らばった欠片を手に入れる。',before:{title:'長い夜に小さな火を',text:'残火の門は近づく光を飲み込んでいた。最後の欠片は炉に囚われ、昔の近衛の姿をした霧が守っている。魔術師がキャンプの小さな灯りを掲げると、仲間の影が一本の道につながった。',line:'夜より大きな炎はいらない。この光を、一人から次の一人へ渡せればいい。'},after:{title:'八人の手、一つの光',text:'炉の火が金色に変わり、四つの欠片が仲間の間を巡る。王座への門が開いた。皆が手を伸ばし、欠片に自分のぬくもりを覚えさせる。欠けた星の核は、まだ石王の胸の中だ。',line:'もう独りで背負わせない。さあ、最後の灯りをともしに行こう。'}},
{speaker:'warden',goal:'古の石王と霧の近衛を倒し、星の核を解放する。',before:{title:'王座に残った最後の一人',text:'石王が立ち上がり、割れた胸甲から黒い霧があふれる。「下がれ。私が守る。」王は最後の命令を繰り返していた。符石の番人には、その奥の助けを求める声が聞こえた。四つの欠片が光る。侵された殻を砕けば、星の核に届くはずだ。',line:'あなたは十分に守ってくれました。今度は、私たちが前に立ちます。'},after:{title:'独りではない星の光',text:'石の鎧が崩れ、星の核と四つの欠片が一つになった。霧が消え、王は初めて両手を下ろす。森に鳥の声が戻り、橋の灯りが次々とともる。キャンプに戻った皆は火に薪を足し、静かな守護者のために席を一つ空けた。',line:'これが新しい約束。誰も独りで見張らなくていい。明日の道も、一緒に歩もう。'}}
]};
function chapterText(index){return STORY[language][index];}
